Adds autosave option to proxyWithHistory
pmndrs/valtio pull request #227
Opened 2021-08-28 09:11 UTC by promontis

2021-08-28 23:01 UTC, dai-shi requested changes
Hi, thanks for suggestion. I wanted proxyWithHistory to be fully customizable, but this part `subscribe` wasn't customizable.
Here're suggestions to cover your use case and more.
Please let me know if you have a better name for the second argument.

2021-08-28 23:18 UTC, promontis commented
@dai-shi really liked your suggestions! I think `skipSubscribe` is a better name, can't think of a better one.

2021-08-28 23:39 UTC, dai-shi commented
oops, would you please run prettier?

2021-08-29 08:38 UTC, promontis commented
@dai-shi done

2021-08-29 08:57 UTC, dai-shi approved these changes

2021-08-29 08:58 UTC, merged