Improve non-proxy error
pmndrs/valtio pull request #26
Opened 2020-11-23 07:48 UTC by Aslemammad

@dai-shi, I think we should write tests for errors, What's your idea?

2020-11-23 07:50 UTC, dai-shi commented
> I think we should write tests for errors, What's your idea?

It's definitely desirable.

2020-11-23 08:14 UTC, Aslemammad commented
> > I think we should write tests for errors, What's your idea?
> 
> It's definitely desirable.

I'll work on it in an another PR.

2020-11-23 14:47 UTC, Aslemammad commented
@dai-shi How is it now?

2020-11-24 00:31 UTC, dai-shi requested changes
As far as I confirm with https://xem.github.io/terser-online/,
`isProduction` fails to minify the production code.
Please make it inline too.

2020-11-24 00:31 UTC, dai-shi commented on src/vanilla.ts
> +  typeof process === 'object' && process.env.NODE_ENV === 'production'
```suggestion
  typeof process !== 'object' || process.env.NODE_ENV === 'production'
```
You failed to invert the logic. 😄

2020-11-24 04:24 UTC, Aslemammad commented on src/vanilla.ts
> +  typeof process === 'object' && process.env.NODE_ENV === 'production'
Yea, I forgot. thanks.

2020-11-24 04:37 UTC, Aslemammad commented
@dai-shi I made isProduction inline now.

2020-11-24 06:50 UTC, dai-shi approved these changes
Thanks for adjustment!

2020-11-24 06:51 UTC, Aslemammad commented
@dai-shi Thanks.

2020-11-24 06:52 UTC, dai-shi commented
What would happen if one does `useProxy({})`?
We'd want to invoke `getVersion()` at the beginning. (and we need another `if`. 🤷‍♂️ )

2020-11-24 07:12 UTC, Aslemammad commented
jest fail tests: Error: Please use proxy object Jest in useProxy

2020-11-24 07:17 UTC, dai-shi commented
That's good. Let's merge this in.
Thanks for your contribution!

2020-11-24 07:18 UTC, Aslemammad commented
Thanks for the merging.

2020-11-24 07:18 UTC, merged