[docs] Improve codesandbox style
pmndrs/valtio pull request #396
Opened 2022-03-23 12:12 UTC by LuckyPigeon

The current `codesandbox` iframe can be improved by font sizing, top & bottom padding, and more.
Here is the before & after

before:
![image](https://user-images.githubusercontent.com/32315294/159696228-cecde04b-5c04-42a6-a406-3cddeda03023.png)

after:
![image](https://user-images.githubusercontent.com/32315294/159696240-4550c0e1-e14f-4873-a422-454d4f4f81aa.png)

2022-03-23 15:32 UTC, roguesherlock reviewed
Looks good. I was wondering if we can write a remark plugin to append those query params to codesandbox url in the post? That way users wouldn't have to append styling params to codesandbox urls every time. Does it makes sense ?

2022-03-24 04:31 UTC, roguesherlock commented
@LuckyPigeon I think we can get around this buy writing our own remark plugin. That plugin should go before oembed plugin. That way, it'll grab any sandbox url and add our query params. It should looks something like this.

```
const remarkPlugins: U.PluggableList = [
  [
    remarkCodeSandboxURLUpdater, // <----- our own custom remark plugin
    // @ts-expect-error
    remarkEmbedder,
    {
      handleError: handleEmbedderError,
      handleHTML: handleEmbedderHtml,
      transformers: [oembedTransformer],
    },
  ],
];
```

```
const remarkCodeSandboxURLUpdater = (options = {}) => {
   // find links which pass codesandbox domain
   // replace links with our query
}
```

Does it makes sense?
Let me know if you need help with writing the plugin (I'd start by looking at how other remark plugins are implemented, https://github.com/remarkjs/remark/blob/main/doc/plugins.md)

2022-04-03 03:44 UTC, dai-shi requested changes
@LuckyPigeon Will you be able to work on the suggested change?

2022-04-03 05:11 UTC, LuckyPigeon commented
@dai-shi 
Sure! I'm looking at the implementation of plugins. I think it will take some time. This can merge first.

2022-04-03 05:42 UTC, dai-shi commented
Great to hear that. We don't plan to merge this as is. Please take your time.
If you have questions about the implementation, @roguesherlock would be able to help.

2022-04-04 03:49 UTC, roguesherlock commented
yes. let me know if you have any questions or need any help :)

2022-04-21 12:31 UTC, dai-shi commented
Can close in favor of #437, right?

2022-04-21 12:31 UTC, closed without merging